// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAw3ApGzXbRuGI9Af7Bp_Sp2fRdznYnj2o',
    appId: '1:361536462767:web:a704c864edb6414f83595a',
    messagingSenderId: '361536462767',
    projectId: 'houseparty-app-cd143',
    authDomain: 'houseparty-app-cd143.firebaseapp.com',
    storageBucket: 'houseparty-app-cd143.appspot.com',
    measurementId: 'G-T273X4GQHK',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDF2hiJiBaG7lvRA6H2hWGHGXfloAtEdoc',
    appId: '1:361536462767:android:a1f17866792bcd8a83595a',
    messagingSenderId: '361536462767',
    projectId: 'houseparty-app-cd143',
    storageBucket: 'houseparty-app-cd143.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCFv6rw-Kpw0KRM1vy39CFc55fu8yWV1ko',
    appId: '1:361536462767:ios:cf9dc3f8b9040ef083595a',
    messagingSenderId: '361536462767',
    projectId: 'houseparty-app-cd143',
    storageBucket: 'houseparty-app-cd143.appspot.com',
    iosBundleId: 'com.example.frontend',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCFv6rw-Kpw0KRM1vy39CFc55fu8yWV1ko',
    appId: '1:361536462767:ios:cf9dc3f8b9040ef083595a',
    messagingSenderId: '361536462767',
    projectId: 'houseparty-app-cd143',
    storageBucket: 'houseparty-app-cd143.appspot.com',
    iosBundleId: 'com.example.frontend',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAw3ApGzXbRuGI9Af7Bp_Sp2fRdznYnj2o',
    appId: '1:361536462767:web:b6e79e262368dbf783595a',
    messagingSenderId: '361536462767',
    projectId: 'houseparty-app-cd143',
    authDomain: 'houseparty-app-cd143.firebaseapp.com',
    storageBucket: 'houseparty-app-cd143.appspot.com',
    measurementId: 'G-ZE2X9P7VN4',
  );

}